# for some reason the common approach fails
common: &common
  solr:
    hostname: ec2-107-21-71-243.compute-1.amazonaws.com
    port: 8080
    log_level: WARNING
production:
  solr:
    hostname: ec2-107-21-71-243.compute-1.amazonaws.com
    port: 8080
    path: /solr/dubsar

development:
  solr:
    hostname: solr-server
    port: 80
    path: /solr/dubsar

test:
  <<: *common

